name: Docusaurus CI

permissions:
  contents: read
  security-events: write

on:
    push:
        branches:
            - main
            - 'feature/**'
    
    pull_request:
        branches:
            - main

env:
    IMAGE_NAME: msiddhartha1600/docusaurus-homelab-docs

jobs:

    ci:
        if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request' || startsWith(github.ref, 'refs/heads/feature/') 
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout
              uses: actions/checkout@v6
            
            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                node-version: 20
            - name: Cache npm
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            
            - name: Install deps
              run: npm ci
            
            - name: Build Docusaurus
              run: npm run build
            
            - name: Run Unit Tests (if any)
              run: |
                if [ -f package.json ] && jq -e '.scripts.test' package.json > /dev/null; then
                    npm test
                else
                    echo "No Tests found, skipping"
                fi

            # ----- SAST (CodeQL) -----------
            - name: Initialize CodeQL
              uses: github/codeql-action/init@v4
              with:
                languages: javascript
            
            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v4

    # pr-build:
    #     if: github.event_name == 'pull_request'
    #     runs-on: ubuntu-22.04

    #     steps:
    #       - name: Checkout
    #         uses: actions/checkout@v6
          
          
            
            
