name: Docusaurus CI

permissions:
  contents: read
  security-events: write

on:
    push:
        branches:
            - master
            - 'feature/**'
    
    pull_request:
        branches:
            - master

env:
    IMAGE_NAME: msiddhartha1600/docusaurus-homelab-docs

jobs:

    ci:
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/feature/') || github.event_name=='pull_request'
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout
              uses: actions/checkout@v6
            
            - name: Setup Node
              uses: actions/setup-node@v6
              with:
                node-version: 20
                cache: npm # Caching npm dependencies at ~./npm
                cache-dependency-path: package-lock.json #package-lock.json file is cached for faster builds
            
            - name: Install deps
              run: npm ci --prefer-offline --no-audit

            - name: Run npm audit (fail on critical)
              run: |
                npm audit --audit-level=critical

            
            - name: Build Docusaurus
              run: npm run build
            
            - name: Run Unit Tests (if any)
              run: |
                if [ -f package.json ] && jq -e '.scripts.test' package.json > /dev/null; then
                    npm test
                else
                    echo "No Tests found, skipping"
                fi
            
            - name: Archive Test Results
              uses: actions/upload-artifact@v7
              with:
                name: Unit-Test-Results
                path: test-results
                retention-days: 5

            - name: Report Test Coverage
              run: npm run coverage
            
            - name: Archive Coverage Report
              uses: actions/upload-artifact@v7
              with:
                name: Code-Coverage-Result
                path: coverage
                retention-days: 5
    
    # codeql:
    #     needs: ci
    #     name: CodeQL Scan
    #     runs-on: ubuntu-22.04

    #     if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'

        
    #     steps:
    #         - name: Checkout
    #           uses: actions/checkout@v6
            
    #         - name: Init CodeQL
    #           uses: github/codeql-action/init@v4
    #           with:
    #             languages: javascript
            
    #         - name: Autobuild
    #           uses: github/codeql-action/autobuild@v4

    #         - name: Perform CodeQL Analysis
    #           uses: github/codeql-action/analyze@v4

    semgrep:
      runs-on: ubuntu-latest
      container:
        image: semgrep/semgrep

      steps:
        - name: Checkout Code
          uses: actions/checkout@v6

        - name: Run Semgrep
          run: |
                semgrep ci \
                  --config=p/security-audit \
                  --config=p/secrets\
                  --config=.semgrep.yml\
                  --sarif --output=semgrep.sarif
        
        - name: Upload SARIF file
          uses: github/codeql-action/upload-sarif@v4
          with:
            sarif_file: semgrep.sarif
          if: always()
    

    
    pr-build:
        needs: ci
        name: PR Docker build
        runs-on: ubuntu-22.04

        if: github.event_name=='pull_request'

        steps:
            - name: Checkout
              uses: actions/checkout@v6    

            - name: Build Docker Image
              run: |
                docker build -t $IMAGE_NAME:pr-${{ github.event.number }} .
            
            - name: Trivy Scan (on PR)
              uses: aquasecurity/trivy-action@v0.36.0
              with: 
                image-ref: ${{ env.IMAGE_NAME }}:pr-${{ github.event.number }}
                format: table
                exit-code: 1
                severity: CRITICAL,HIGH